// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHFAakJ_lryO1Y7u8CN25azZN_NMFhDvQ',
    appId: '1:800322458853:web:4da960e6ec089bdbd5700c',
    messagingSenderId: '800322458853',
    projectId: 'fitness-app-bird',
    authDomain: 'fitness-app-bird.firebaseapp.com',
    storageBucket: 'fitness-app-bird.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4S5vNSBdpKcgxPOftX8EfBGxLQCMBB-c',
    appId: '1:800322458853:android:56ca5db215b32c9ad5700c',
    messagingSenderId: '800322458853',
    projectId: 'fitness-app-bird',
    storageBucket: 'fitness-app-bird.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzZAFI-bMe8K7dXzPzf23yjhr3EOxQAA8',
    appId: '1:800322458853:ios:92ac8d8bd92e203bd5700c',
    messagingSenderId: '800322458853',
    projectId: 'fitness-app-bird',
    storageBucket: 'fitness-app-bird.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
